### ISSUE TITLE
Require the wait-for-success config

### ISSUE THREAD

**Issue by weaponsforge** [weaponsforge/render-deploy-action#1]
Require the `wait-for-success` setting.

```
name: My Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true
```
